# Generated by Django 3.2.25 on 2024-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='rooms/'),
            preserve_default=False,
        ),
    ]
