# Generated by Django 3.2.25 on 2024-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240814_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='rooms/default_image.jpg', upload_to='rooms/'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='services',
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(related_name='rooms', to='booking.Tag'),
        ),
    ]
