name: 'Terraform Development Plan and Apply'

on:
  push:
    paths:
      - 'terraform/development/**'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/development/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      working-directory: terraform/development
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/development
      run: terraform plan -out=tfplan.binary

    - name: Upload Plan for Review
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: terraform/development/tfplan.binary

  manual-approval:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Await Approval
      uses: chetan/git-prompt@v1
      with:
        prompt: 'Do you want to apply this Terraform plan for development?'

  apply:
    runs-on: ubuntu-latest
    needs: manual-approval
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download Plan
      uses: actions/download-artifact@v3
      with:
        name: tfplan

    - name: Terraform Apply
      working-directory: terraform/development
      run: terraform apply "tfplan.binary"
