name: Deploy Django App to Azure

on:
  push:
    paths:
      - 'hotel_pegaso/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'as-pegaso-dev-westeu-001'  # Sostituisci con il nome della tua app su Azure
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: hotel_pegaso

    # - name: Run Django Migrations on Azure
    #   run: |
    #     az webapp ssh --name as-pegaso-dev-westeu-001 --resource-group rg-pegaso-dev-westeu-001 --command "python manage.py migrate"

    # - name: Collect Static Files on Azure
    #   run: |
    #     az webapp ssh --name as-pegaso-dev-westeu-001 --resource-group rg-pegaso-dev-westeu-001 --command "python manage.py collectstatic --noinput"
