name: Deploy Django App to Azure

on:
  push:
    paths:
      - 'hotel_pegaso/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-service-name'  # Sostituisci con il nome della tua app su Azure
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Run Django Migrations on Azure
      run: |
        az webapp ssh --name your-app-service-name --resource-group your-resource-group-name --command "python manage.py migrate"

    - name: Collect Static Files on Azure
      run: |
        az webapp ssh --name your-app-service-name --resource-group your-resource-group-name --command "python manage.py collectstatic --noinput"
